// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

#include "common.hpp"

// NOTE (mristin):
// We use MultiByteToWideChar and WideCharToMulitByte from <windows.h> on Windows
// as std::codecvt is not robust enough on Windows, and produces invalid UTF-16
// sequences as std::wstring. See:
// https://stackoverflow.com/questions/2573834/c-convert-string-or-char-to-wstring-or-wchar-t,
// especially the comment:
// https://stackoverflow.com/questions/2573834/c-convert-string-or-char-to-wstring-or-wchar-t#comment110447503_18597384
#ifdef _WIN32
#include <windows.h>
#include <limits>
#include <cstring>
#else
// NOTE (mristin):
// We use codecvt although it has been deprecated. There has been not
// suitable replacement proposed yet, so we simply stick to it
// until there is. See:
// https://stackoverflow.com/questions/42946335/deprecated-header-codecvt-replacement
#include <codecvt>
#include <locale>
#endif

namespace aas_core {
namespace aas_3_0 {
namespace common {

std::wstring Concat(
  const std::wstring& part0,
  const std::wstring& part1
) {
  size_t size = 0;
  size += part0.size();
  size += part1.size();

  std::wstring result;
  result.reserve(size);

  result.append(part0);
  result.append(part1);

  return result;
}

std::wstring Concat(
  const std::wstring& part0,
  const std::wstring& part1,
  const std::wstring& part2
) {
  size_t size = 0;
  size += part0.size();
  size += part1.size();
  size += part2.size();

  std::wstring result;
  result.reserve(size);

  result.append(part0);
  result.append(part1);
  result.append(part2);

  return result;
}

std::wstring Concat(
  const std::wstring& part0,
  const std::wstring& part1,
  const std::wstring& part2,
  const std::wstring& part3
) {
  size_t size = 0;
  size += part0.size();
  size += part1.size();
  size += part2.size();
  size += part3.size();

  std::wstring result;
  result.reserve(size);

  result.append(part0);
  result.append(part1);
  result.append(part2);
  result.append(part3);

  return result;
}

std::wstring Concat(
  const std::wstring& part0,
  const std::wstring& part1,
  const std::wstring& part2,
  const std::wstring& part3,
  const std::wstring& part4
) {
  size_t size = 0;
  size += part0.size();
  size += part1.size();
  size += part2.size();
  size += part3.size();
  size += part4.size();

  std::wstring result;
  result.reserve(size);

  result.append(part0);
  result.append(part1);
  result.append(part2);
  result.append(part3);
  result.append(part4);

  return result;
}

std::wstring Concat(
  const std::wstring& part0,
  const std::wstring& part1,
  const std::wstring& part2,
  const std::wstring& part3,
  const std::wstring& part4,
  const std::wstring& part5
) {
  size_t size = 0;
  size += part0.size();
  size += part1.size();
  size += part2.size();
  size += part3.size();
  size += part4.size();
  size += part5.size();

  std::wstring result;
  result.reserve(size);

  result.append(part0);
  result.append(part1);
  result.append(part2);
  result.append(part3);
  result.append(part4);
  result.append(part5);

  return result;
}

std::wstring Concat(
  const std::wstring& part0,
  const std::wstring& part1,
  const std::wstring& part2,
  const std::wstring& part3,
  const std::wstring& part4,
  const std::wstring& part5,
  const std::wstring& part6
) {
  size_t size = 0;
  size += part0.size();
  size += part1.size();
  size += part2.size();
  size += part3.size();
  size += part4.size();
  size += part5.size();
  size += part6.size();

  std::wstring result;
  result.reserve(size);

  result.append(part0);
  result.append(part1);
  result.append(part2);
  result.append(part3);
  result.append(part4);
  result.append(part5);
  result.append(part6);

  return result;
}

std::wstring Concat(
  const std::wstring& part0,
  const std::wstring& part1,
  const std::wstring& part2,
  const std::wstring& part3,
  const std::wstring& part4,
  const std::wstring& part5,
  const std::wstring& part6,
  const std::wstring& part7
) {
  size_t size = 0;
  size += part0.size();
  size += part1.size();
  size += part2.size();
  size += part3.size();
  size += part4.size();
  size += part5.size();
  size += part6.size();
  size += part7.size();

  std::wstring result;
  result.reserve(size);

  result.append(part0);
  result.append(part1);
  result.append(part2);
  result.append(part3);
  result.append(part4);
  result.append(part5);
  result.append(part6);
  result.append(part7);

  return result;
}

std::wstring Concat(
  const std::wstring& part0,
  const std::wstring& part1,
  const std::wstring& part2,
  const std::wstring& part3,
  const std::wstring& part4,
  const std::wstring& part5,
  const std::wstring& part6,
  const std::wstring& part7,
  const std::wstring& part8
) {
  size_t size = 0;
  size += part0.size();
  size += part1.size();
  size += part2.size();
  size += part3.size();
  size += part4.size();
  size += part5.size();
  size += part6.size();
  size += part7.size();
  size += part8.size();

  std::wstring result;
  result.reserve(size);

  result.append(part0);
  result.append(part1);
  result.append(part2);
  result.append(part3);
  result.append(part4);
  result.append(part5);
  result.append(part6);
  result.append(part7);
  result.append(part8);

  return result;
}

std::wstring Concat(
  const std::wstring& part0,
  const std::wstring& part1,
  const std::wstring& part2,
  const std::wstring& part3,
  const std::wstring& part4,
  const std::wstring& part5,
  const std::wstring& part6,
  const std::wstring& part7,
  const std::wstring& part8,
  const std::wstring& part9
) {
  size_t size = 0;
  size += part0.size();
  size += part1.size();
  size += part2.size();
  size += part3.size();
  size += part4.size();
  size += part5.size();
  size += part6.size();
  size += part7.size();
  size += part8.size();
  size += part9.size();

  std::wstring result;
  result.reserve(size);

  result.append(part0);
  result.append(part1);
  result.append(part2);
  result.append(part3);
  result.append(part4);
  result.append(part5);
  result.append(part6);
  result.append(part7);
  result.append(part8);
  result.append(part9);

  return result;
}

std::wstring Concat(
  const std::wstring& part0,
  const std::wstring& part1,
  const std::wstring& part2,
  const std::wstring& part3,
  const std::wstring& part4,
  const std::wstring& part5,
  const std::wstring& part6,
  const std::wstring& part7,
  const std::wstring& part8,
  const std::wstring& part9,
  const std::wstring& part10
) {
  size_t size = 0;
  size += part0.size();
  size += part1.size();
  size += part2.size();
  size += part3.size();
  size += part4.size();
  size += part5.size();
  size += part6.size();
  size += part7.size();
  size += part8.size();
  size += part9.size();
  size += part10.size();

  std::wstring result;
  result.reserve(size);

  result.append(part0);
  result.append(part1);
  result.append(part2);
  result.append(part3);
  result.append(part4);
  result.append(part5);
  result.append(part6);
  result.append(part7);
  result.append(part8);
  result.append(part9);
  result.append(part10);

  return result;
}

std::wstring Concat(
  const std::wstring& part0,
  const std::wstring& part1,
  const std::wstring& part2,
  const std::wstring& part3,
  const std::wstring& part4,
  const std::wstring& part5,
  const std::wstring& part6,
  const std::wstring& part7,
  const std::wstring& part8,
  const std::wstring& part9,
  const std::wstring& part10,
  const std::wstring& part11
) {
  size_t size = 0;
  size += part0.size();
  size += part1.size();
  size += part2.size();
  size += part3.size();
  size += part4.size();
  size += part5.size();
  size += part6.size();
  size += part7.size();
  size += part8.size();
  size += part9.size();
  size += part10.size();
  size += part11.size();

  std::wstring result;
  result.reserve(size);

  result.append(part0);
  result.append(part1);
  result.append(part2);
  result.append(part3);
  result.append(part4);
  result.append(part5);
  result.append(part6);
  result.append(part7);
  result.append(part8);
  result.append(part9);
  result.append(part10);
  result.append(part11);

  return result;
}

std::wstring Concat(
  const std::wstring& part0,
  const std::wstring& part1,
  const std::wstring& part2,
  const std::wstring& part3,
  const std::wstring& part4,
  const std::wstring& part5,
  const std::wstring& part6,
  const std::wstring& part7,
  const std::wstring& part8,
  const std::wstring& part9,
  const std::wstring& part10,
  const std::wstring& part11,
  const std::wstring& part12
) {
  size_t size = 0;
  size += part0.size();
  size += part1.size();
  size += part2.size();
  size += part3.size();
  size += part4.size();
  size += part5.size();
  size += part6.size();
  size += part7.size();
  size += part8.size();
  size += part9.size();
  size += part10.size();
  size += part11.size();
  size += part12.size();

  std::wstring result;
  result.reserve(size);

  result.append(part0);
  result.append(part1);
  result.append(part2);
  result.append(part3);
  result.append(part4);
  result.append(part5);
  result.append(part6);
  result.append(part7);
  result.append(part8);
  result.append(part9);
  result.append(part10);
  result.append(part11);
  result.append(part12);

  return result;
}

std::wstring Concat(
  const std::wstring& part0,
  const std::wstring& part1,
  const std::wstring& part2,
  const std::wstring& part3,
  const std::wstring& part4,
  const std::wstring& part5,
  const std::wstring& part6,
  const std::wstring& part7,
  const std::wstring& part8,
  const std::wstring& part9,
  const std::wstring& part10,
  const std::wstring& part11,
  const std::wstring& part12,
  const std::wstring& part13
) {
  size_t size = 0;
  size += part0.size();
  size += part1.size();
  size += part2.size();
  size += part3.size();
  size += part4.size();
  size += part5.size();
  size += part6.size();
  size += part7.size();
  size += part8.size();
  size += part9.size();
  size += part10.size();
  size += part11.size();
  size += part12.size();
  size += part13.size();

  std::wstring result;
  result.reserve(size);

  result.append(part0);
  result.append(part1);
  result.append(part2);
  result.append(part3);
  result.append(part4);
  result.append(part5);
  result.append(part6);
  result.append(part7);
  result.append(part8);
  result.append(part9);
  result.append(part10);
  result.append(part11);
  result.append(part12);
  result.append(part13);

  return result;
}

std::wstring Concat(
  const std::wstring& part0,
  const std::wstring& part1,
  const std::wstring& part2,
  const std::wstring& part3,
  const std::wstring& part4,
  const std::wstring& part5,
  const std::wstring& part6,
  const std::wstring& part7,
  const std::wstring& part8,
  const std::wstring& part9,
  const std::wstring& part10,
  const std::wstring& part11,
  const std::wstring& part12,
  const std::wstring& part13,
  const std::wstring& part14
) {
  size_t size = 0;
  size += part0.size();
  size += part1.size();
  size += part2.size();
  size += part3.size();
  size += part4.size();
  size += part5.size();
  size += part6.size();
  size += part7.size();
  size += part8.size();
  size += part9.size();
  size += part10.size();
  size += part11.size();
  size += part12.size();
  size += part13.size();
  size += part14.size();

  std::wstring result;
  result.reserve(size);

  result.append(part0);
  result.append(part1);
  result.append(part2);
  result.append(part3);
  result.append(part4);
  result.append(part5);
  result.append(part6);
  result.append(part7);
  result.append(part8);
  result.append(part9);
  result.append(part10);
  result.append(part11);
  result.append(part12);
  result.append(part13);
  result.append(part14);

  return result;
}

std::wstring Concat(
  const std::wstring& part0,
  const std::wstring& part1,
  const std::wstring& part2,
  const std::wstring& part3,
  const std::wstring& part4,
  const std::wstring& part5,
  const std::wstring& part6,
  const std::wstring& part7,
  const std::wstring& part8,
  const std::wstring& part9,
  const std::wstring& part10,
  const std::wstring& part11,
  const std::wstring& part12,
  const std::wstring& part13,
  const std::wstring& part14,
  const std::wstring& part15
) {
  size_t size = 0;
  size += part0.size();
  size += part1.size();
  size += part2.size();
  size += part3.size();
  size += part4.size();
  size += part5.size();
  size += part6.size();
  size += part7.size();
  size += part8.size();
  size += part9.size();
  size += part10.size();
  size += part11.size();
  size += part12.size();
  size += part13.size();
  size += part14.size();
  size += part15.size();

  std::wstring result;
  result.reserve(size);

  result.append(part0);
  result.append(part1);
  result.append(part2);
  result.append(part3);
  result.append(part4);
  result.append(part5);
  result.append(part6);
  result.append(part7);
  result.append(part8);
  result.append(part9);
  result.append(part10);
  result.append(part11);
  result.append(part12);
  result.append(part13);
  result.append(part14);
  result.append(part15);

  return result;
}

std::string WstringToUtf8(const std::wstring& text) {
  #ifdef _WIN32
  // Inspired by:
  // https://stackoverflow.com/a/69410299/1600678

  if (text.empty()) {
    return "";
  }

  // NOTE (mristin):
  // We put `max` into parentheses to avoid conflicts with
  // <windows.h> `max` macro, see:
  // https://stackoverflow.com/questions/11544073/how-do-i-deal-with-the-max-macro-in-windows-h-colliding-with-max-in-std

  const size_t text_size = text.size();
  if (text_size > (std::numeric_limits<int>::max)()) {
    std::ostringstream ss;
    ss
      << "The size of the text to be converted to UTF-8, "
      << text_size << " exceeds the maximum int value "
      << (std::numeric_limits<int>::max)();
    throw std::out_of_range(ss.str());
  }
  const int text_size_int = static_cast<int>(text_size);

  const auto size_needed = WideCharToMultiByte(
    CP_UTF8,
    0,
    &(text[0]),
    text_size_int,
    nullptr,
    0,
    nullptr,
    nullptr
  );

  if (size_needed <= 0) {
    throw std::runtime_error(
      "WideCharToMultiByte() failed: " + std::to_string(size_needed)
    );
  }

  std::string result(size_needed, 0);

  WideCharToMultiByte(
    CP_UTF8,
    0,
    &(text[0]),
    text_size_int,
    &(result[0]),
    size_needed,
    nullptr, 
    nullptr
  );

  return result;
  #else
  // NOTE (mristin):
  // We use codecvt although it has been deprecated. There has been not
  // suitable replacement proposed yet, so we simply stick to it
  // until there is. See:
  // https://stackoverflow.com/questions/42946335/deprecated-header-codecvt-replacement

  std::wstring_convert<std::codecvt_utf8<wchar_t> > conv;
  return conv.to_bytes(text.str()));
  #endif
}

std::wstring Utf8ToWstring(
  const char* utf8_text,
  size_t utf8_text_size
) {
  #ifdef _WIN32
  // NOTE (mristin):
  // We have to use MultiByteToWideChar from <windows.h> on Windows
  // as std::codecvt is not robust enough on Windows and produces invalid UTF-16
  // sequences as std::wstring. See:
  // https://stackoverflow.com/questions/2573834/c-convert-string-or-char-to-wstring-or-wchar-t,
  // especially the comment:
  // https://stackoverflow.com/questions/2573834/c-convert-string-or-char-to-wstring-or-wchar-t#comment110447503_18597384

  // Inspired by:
  // https://stackoverflow.com/a/69410299/1600678

  if (utf8_text_size == std::string::npos) {
    utf8_text_size = strlen(utf8_text);
  }

  // NOTE (mristin):
  // We put `max` into parentheses to avoid conflicts with
  // <windows.h> `max` macro, see:
  // https://stackoverflow.com/questions/11544073/how-do-i-deal-with-the-max-macro-in-windows-h-colliding-with-max-in-std

  if (utf8_text_size > (std::numeric_limits<int>::max)()) {
    std::ostringstream ss;
    ss
      << "The size of the UTF-8 text to be converted to wide string, "
      << utf8_text_size << " exceeds the maximum int value "
      << (std::numeric_limits<int>::max)();
    throw std::out_of_range(ss.str());
  }
  const int utf8_text_size_int = static_cast<int>(utf8_text_size);

  const auto size_needed = MultiByteToWideChar(
    CP_UTF8,
    0,
    utf8_text,
    utf8_text_size_int,
    nullptr,
    0
  );
  if (size_needed <= 0) {
    throw std::runtime_error(
      "MultiByteToWideChar() failed: " + std::to_string(size_needed)
    );
  }

  std::wstring result(size_needed, 0);

  MultiByteToWideChar(
    CP_UTF8,
    0,
    utf8_text,
    utf8_text_size_int,
    &(result[0]),
    size_needed
  );

  return result;

  #else
  // NOTE (mristin):
  // We use codecvt although it has been deprecated. There has been not
  // suitable replacement proposed yet, so we simply stick to it
  // until there is. See:
  // https://stackoverflow.com/questions/42946335/deprecated-header-codecvt-replacement

  std::wstring_convert<std::codecvt_utf8<wchar_t>,wchar_t> conv;
  return conv.from_bytes(utf8_text);
  #endif
}

std::wstring Utf8ToWstring(const std::string& utf8_text) {
  return Utf8ToWstring(&(utf8_text[0]), utf8_text.size());
}

}  // namespace common
}  // namespace aas_3_0
}  // namespace aas_core

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
