name: CI-for-dev-scripts

on:
  push:
    branches: [ master, main ]
    tags: [ "**" ]
    paths:
      - dev_scripts/**
  pull_request:
    branches: [ "**" ]
    paths:
      - dev_scripts/**

jobs:
  Execute-continuous-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -e dev_scripts[dev]

      - name: Run checks
        run: |
          python3 dev_scripts/continuous_integration_of_dev_scripts/precommit.py
