name: Doc

on:
  push:
    branches:
      - main
      - mristin/Kick-off

jobs:
  Generate-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          doxyfile-path: "./Doxyfile"
          working-directory: "."

      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./local-built-doc/html
